export enum FILE_LEVEL {
  COMPANY = "COMPANY",
  EMPLOYEE = "EMPLOYEE",
  REGION = "REGION",
}

export enum FILE_FOLDER {
  ADDRESS = "ADDRESS",
  AVATAR = "AVATAR",
  FAQS = "FAQS",
  FILE = "FILE",
  LANGUAGE = "LANGUAGE",
  PAYSLIP_CONFIG_BG_IMAGE = "PAYSLIP_CONFIG_BG_IMAGE",
  PAYSLIP_CONFIG_WATER_MARK = "PAYSLIP_CONFIG_WATER_MARK",
  SETTING = "SETTING",
}
