import { zodResolver } from "@hookform/resolvers/zod"
import { useIsMutating } from "@tanstack/react-query"
import { useCallback, useEffect, useMemo, useState } from "react"
import { FormProvider, useForm } from "react-hook-form"
import { useTranslation } from "react-i18next"

import { Button } from "~/hr-port/components/base/button"
import { DialogFooter } from "~/hr-port/components/base/dialog"
import AppDialog from "~/hr-port/components/ui/app-dialog/app-dialog"
import { AppDialogOpenProps } from "~/hr-port/components/ui/app-dialog/types"
import FooterButton from "~/hr-port/components/ui/footer-button-group/footer-button"
import FooterButtonGroup from "~/hr-port/components/ui/footer-button-group/footer-button-group"
import { documentKeys } from "~/hr-port/features/documents/api/query-key-factories"
import { Field } from "~/hr-port/features/dynamic-form/types"
import { Attributes } from "~/hr-port/features/dynamic-form/utils/attribute"
import { resetHiddenFieldValues } from "~/hr-port/features/dynamic-form/utils/convert-form-data"
import { getDefaultValueForFields } from "~/hr-port/features/dynamic-form/utils/field"
import { getSchemaFromFields } from "~/hr-port/features/dynamic-form/utils/rule"
import FormDynamicField from "~/hr-port/features/profiles/components/form-dynamic-field/form-dynamic-field"
import useGetDevice from "~/hr-port/hooks/use-get-device"

import ConfirmUpdateDataTableItemDialog from "./confirm-update-data-table-item-dialog"

export type AddEditDataTableItemDialogProps = {
  columnSettings: Field[]
  defaultValues?: Record<string, any>
  onSubmit: (values?: Record<string, any>) => void | Promise<void>
  title: string
} & AppDialogOpenProps

const AddEditDataTableItemDialog = (props: AddEditDataTableItemDialogProps) => {
  const { largeMobileAndSmaller } = useGetDevice()
  const { t } = useTranslation()
  const {
    columnSettings,
    title,
    onSubmit: onSubmitProp,
    open,
    setOpen,
    defaultValues,
  } = props
  const isEdit = !!defaultValues
  const uploadingCount = useIsMutating({
    mutationKey: documentKeys.uploadDocument,
    exact: true,
  })
  const isUploading = uploadingCount > 0

  const [openConfirmDialog, setOpenConfirmDialog] = useState(false)
  const [values, setValues] = useState<Record<string, any>>({})

  const initPayload = useMemo(() => {
    return {
      ...getDefaultValueForFields(columnSettings),
      ...defaultValues,
    }
  }, [columnSettings, defaultValues])

  const methods = useForm({
    mode: "onBlur",
    values: initPayload,
    resolver: zodResolver(getSchemaFromFields(columnSettings)),
  })
  const { handleSubmit } = methods

  const onSubmit = useCallback(
    (formValues: Record<string, any>) => {
      resetHiddenFieldValues({ formValues, fields: columnSettings })
      setValues(formValues)
      setOpenConfirmDialog(true)
    },
    [columnSettings]
  )

  useEffect(() => {
    if (!open) {
      methods.reset(initPayload)
    }
  }, [open, initPayload, methods])

  return (
    <AppDialog title={title} open={open} setOpen={setOpen} position="right">
      <FormProvider {...methods}>
        <form
          onSubmit={(e) => {
            //NOTE: prevent form submitting trigger parent form context
            e.stopPropagation()
            handleSubmit(onSubmit)(e)
          }}
        >
          <div className="grid gap-4">
            {columnSettings
              .filter((item) => {
                const isAutoGenerated = item.attributes.some(
                  (attribute) => attribute.key === Attributes.AUTO_VALUE
                )
                const defaultItemValue = initPayload?.[item.id.toString()]

                if (isEdit) {
                  const hasAutoValue = !isAutoGenerated || !!defaultItemValue
                  return hasAutoValue
                }
                return !isAutoGenerated
              })
              .map((item) => {
                return (
                  <FormDynamicField
                    key={item.id}
                    {...item}
                    vertical
                    isInDialog
                  />
                )
              })}
          </div>
          <DialogFooter className="dialog-footer dialog-padding">
            {!largeMobileAndSmaller && (
              <>
                <Button
                  variant="outline_secondary"
                  className="min-w-[112px]"
                  onClick={() => setOpen(false)}
                >
                  {t("common.button.cancel")}
                </Button>
                <Button
                  type="submit"
                  className="min-w-[112px]"
                  disabled={isUploading}
                >
                  {isEdit ? t("common.button.update") : t("common.button.add")}
                </Button>
              </>
            )}
            {largeMobileAndSmaller && (
              <FooterButtonGroup hasShadow takeSpace={false}>
                <FooterButton
                  variant="outline_secondary"
                  onClick={() => setOpen(false)}
                >
                  {t("common.button.cancel")}
                </FooterButton>
                <FooterButton type="submit">
                  {isEdit ? t("common.button.update") : t("common.button.add")}
                </FooterButton>
              </FooterButtonGroup>
            )}
          </DialogFooter>
        </form>
      </FormProvider>
      <ConfirmUpdateDataTableItemDialog
        isEdit={isEdit}
        payload={values}
        onSubmit={(payloadValues) => {
          onSubmitProp?.(payloadValues)
          setOpen(false)
        }}
        open={openConfirmDialog}
        setOpen={setOpenConfirmDialog}
      />
    </AppDialog>
  )
}
export default AddEditDataTableItemDialog
